import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { TanStackProvider } from "@/providers/TanStackProvider";

const lato = localFont({
  src: [
    {
      path: "./fonts/lato/lato-v24-latin-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/lato/lato-v24-latin-700.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/lato/lato-v24-latin-900.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "edusight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased max-w-[1540px] mx-auto`}>
        <TanStackProvider>
          <Header />
          {children}
          <Footer />
        </TanStackProvider>
      </body>
    </html>
  );
}
